// Generated by https://quicktype.io

export interface Product {
  colors:      Color[];
  price:       number;
  name:        string;
  sizes:       string[];
  description: string;
  fullDescription?:string;
  id:          string;
}

export interface Color {
  img:   string;
  color: string;
}
